service: sls-state-bug
provider:
  name: aws
  runtime: python3.7
  memorySize: 2048
  stage: dev
  region: us-east-1
  versionFunctions: false
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "logs:PutLogEvents"
      Resource: ["*"]

plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: true
    slim: true

package:
  exclude:
    - node_modules/**
    - "!node_modules/node-fetch/**"
    - "venv/**"

# Lambda Functions Starts
# ======================General functions for both user and admin starts =======================================================================
functions:
  get_user_data:
    handler: app.get_user_id.get_user_data
    events:
      - http:
          path: gen-user-data
          method: get
          cors: true
  gen_os_random:
    handler: app.os_myrand.get_user_data
    events:
      - http:
          path: gen-os-rand
          method: get
          cors: true
  gen_pass:
    handler: app.password_gen.gen_pass
    events:
      - http:
          path: gen-pass
          method: post
          cors: true